### ISSUE TITLE
UnsupportedMethodError while creating a new calendar

### ISSUE THREAD

**Issue by faridanoosheh** [pat/calendav#2]
A try to create new calendar results in the following error: 
```
client.calendars.create(identifier, attributes)
=> HTTP::Request::UnsupportedMethodError (unknown method: mkcalendar)
```
which seems to be form this line https://github.com/pat/calendav/blob/49308b34616ac14b2fb5f7f7f3c051c48310371c/lib/calendav/endpoint.rb#L31
The server does not know the `mkcalendar`.

I am using NextCould as the CalDav server. I had same problem with other CalDav servers like Baikal and DAViCal.
Thanks.

**Comment by pat** [comment]
Thanks for reporting this issue Farid. Are you finding other operations (e.g. listing existing calendars) are working?

I'm also wondering if it's a limitation in these providers - for example, Google supports a lot of CalDAV, but _not_ the creation of calendars. It's frustrating! I'll see if I can reproduce the issue though with one of the servers you've mentioned.

**Comment by pat** [comment]
I've gotten Baikal running locally, and managed to get Calendav working well with it - the key is determining the host value for your credentials. In my case, running locally on port 10091, it required the following:

```ruby
credentials = Calendav::Credentials::Standard.new(
  host: "http://localhost:10019/dav.php",
  username: "pat",
  password: "...",
  authentication: :basic_auth
)
```

I also needed to change the WebDAV Authentication Type to be Basic.

<img width="579" alt="Screen Shot 2022-11-05 at 2 17 37 pm" src="https://user-images.githubusercontent.com/4183/200098699-ac8ef342-ce02-4e2a-af5c-0cd7113cb348.png">

For NextCloud, it seems the relevant path [should likely be `/remote.php/dav`](https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#service-discovery). I'm not sure about their authentication approach though.

**Comment by faridanoosheh** [comment]
Thanks @pat   for your reply. 
I have the same for credentials on my local Nextcloud server
```
          credentials =
            Calendav::Credentials::Standard.new(host: http://localhost:8080/remote.php/dav",
                                                username: username,
                                                password: password,
                                                authentication: :basic_auth)
          client = Calendav.client(credentials)
```
then it is fine for `client.calendars.list` or `client.events` methods (list/create/delete/update).
But As I mentioned before I can't create a new calendare.
I wonder if it could be because of [this issue on Nextcloud](https://help.nextcloud.com/t/creating-a-new-calendar-via-curl/58018)

**Comment by pat** [comment]
Good to know at least some parts are working!

What are you passing through as arguments to `client.calendars.create`? The identifier should be something unique and URL-friendly - I usually use `SecureRandom.uuid`.

**Comment by faridanoosheh** [comment]
I think I should look for another reason except Identifier, cause same error with a random identifier:
````
irb(main):209:0> client.calendars.create('new-calendar', {display_name: 'newCalendar'})
Traceback (most recent call last):
        2: from (irb):208
        1: from (irb):209:in `rescue in irb_binding'
HTTP::Request::UnsupportedMethodError (unknown method: mkcalendar)

irb(main):210:0> client.calendars.create(SecureRandom.uuid, {display_name: 'newCalendar'})
Traceback (most recent call last):
        2: from (irb):209
        1: from (irb):210:in `rescue in irb_binding'
HTTP::Request::UnsupportedMethodError (unknown method: mkcalendar)
````

**Comment by faridanoosheh** [comment]
@pat,
It was failing in my case because I am on a older version of ruby (< 2.7) in which HTTP gem does not support MKCALENDAR
it has been added on version 5.0 of http.
So every thing is fine with your gem if we respect ruby version. Otherwise it is necessary to require http '~> 5.0'

Thanks anyway for your answers.

**Comment by pat** [comment]
Ah, well done on debugging that, though I can imagine it's frustrating! I hadn't realised there was that limitation in http. Perhaps I should put a hard limit on the Ruby version requirement for the gem 🤔
